FROM nginx:alpine

# Copy nginx configuration
COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx-frontend.conf /etc/nginx/nginx-frontend.conf

# Copy SSL certificates (if they exist)
COPY docker/ssl /etc/nginx/ssl

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]